package Myplanner;

import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;
import org.testng.annotations.*;
import static org.testng.Assert.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import java.io.File;
import java.time.Duration;

import org.apache.commons.io.FileUtils;

public class crm extends Login {
//  private WebDriver driver;
  private String baseUrl;
  private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();
  private JavascriptExecutor js;

//  @BeforeClass(alwaysRun = true)
//  public void setUp() throws Exception {
//    System.setProperty("webdriver.chrome.driver", "");
//    driver = new ChromeDriver();
//    baseUrl = "https://www.google.com/";
//    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
//    js = (JavascriptExecutor) driver;
//  }

  @Test
  public void testUntitledTestCase() throws Exception {
//    driver.get("https://staging3.ifanow.in/login");
//    driver.findElement(By.id("mat-input-0")).clear();
//    driver.findElement(By.id("mat-input-0")).sendKeys("sonesh.dedhia@manekfinancial.com");
//    driver.findElement(By.id("mat-input-1")).clear();
//    driver.findElement(By.id("mat-input-1")).sendKeys("123#Manek@!");
//    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::span[4]")).click();
//    driver.get("https://staging3.ifanow.in/admin/dashboard");
    driver.findElement(By.xpath("//mat-nav-list[@id='d']/div[2]/div/a[2]/span/span[2]/span")).click();
    driver.get("https://staging3.ifanow.in/admin/research/mutualFund/overview");
    driver.findElement(By.xpath("//mat-nav-list[@id='d']/div[2]/div/a[3]/span/span[2]/span")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-0']/span/mat-panel-title/a/span/span[2]/span")).click();
//    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-0']/span/mat-panel-title/a/span/span[2]/span")).click();
    driver.findElement(By.xpath("//mat-nav-list[@id='d']/div[2]/div/a[5]/span/span[2]/span")).click();
    driver.get("https://staging3.ifanow.in/admin/transactions/mutualFund/crm");
    driver.findElement(By.linkText("CRM")).click();
    driver.get("https://staging3.ifanow.in/admin/transactions/mutualFund/campaign");
    driver.findElement(By.linkText("Campaigns")).click();
    driver.findElement(By.xpath("//mat-sidenav-content[@id='left']/div[2]/app-transactions/div[2]/div/app-mutual-fund-view/div[2]/div/app-multi-transact/div/div/div/div/div/div[2]/button")).click();
    driver.findElement(By.xpath("//input[@formcontrolname=\"campaignName\"]")).sendKeys("cjhasdg");
//    driver.findElement(By.id("mat-input-10")).clear();
//    driver.findElement(By.id("mat-input-10")).sendKeys("P_3");
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div/div[2]/button/span")).click();
    driver.findElement(By.id("mat-expansion-panel-header-4")).click();
    driver.findElement(By.xpath("//input[@placeholder=\"Search Scheme\"]")).sendKeys("axis");
    Thread.sleep(1000);
//    driver.findElement(By.id("mat-input-12")).clear();
//    driver.findElement(By.id("mat-input-12")).sendKeys("axis");
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-120']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//mat-radio-button[@id='mat-radio-45']/label/span/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div/div[2]/button/span")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-6']/span/div")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-506']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div/div[2]/button")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Zerodha Asset Management Private Limited'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-9']/span/div")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-961']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div[2]/div/table/tbody/tr/td[3]/div/div")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div[2]/div/table/tbody/tr[5]/td[3]/div/div/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div/div[2]/button")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-12']/span/div")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-1412']/label/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-1414']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div[2]/div/table/tbody/tr/td[3]/div/div/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div[2]/div/table/tbody/tr[7]/td[3]/div/div/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div/div[2]/button/span")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-15']/span/div")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-1859']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div/div[2]/button/span")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-19']/span/div")).click();
    driver.findElement(By.id("mat-input-17")).click();
    driver.findElement(By.id("mat-input-17")).clear();
    driver.findElement(By.id("mat-input-17")).sendKeys("icic");
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-2763']/label/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-2765']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div/div[2]/button")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-22']/span/div")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Zerodha Asset Management Private Limited'])[1]/following::button[1]")).click();
    driver.findElement(By.id("mat-expansion-panel-header-22")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-23']/span/div")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-23']/span/div")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-23']/span/div")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-4207']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-scheme-detail-multi/div/div[3]/div/div[2]/button/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Zerodha Asset Management Private Limited'])[1]/following::button[1]")).click();
    driver.findElement(By.id("mat-expansion-panel-header-26")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-4966']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//mat-radio-button[@id='mat-radio-213']/label/span/span")).click();
    driver.findElement(By.xpath("//button[@type='undefined']")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div[2]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div[3]/div/div/p")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div[4]/div/div/p")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div[5]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div[6]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div[5]/div/div/p")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div[6]")).click();
    driver.findElement(By.xpath("//img[contains(@src,'https://res.cloudinary.com/futurewise/image/upload/v1730960221/myplanner/Vector55.svg')]")).click();
    driver.findElement(By.xpath("//mat-select[@id='mat-select-4']/div/div[2]/div")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-2971']/span")).click();
    driver.findElement(By.xpath("//img[contains(@src,'https://res.cloudinary.com/futurewise/image/upload/v1730960221/myplanner/Vector55.svg')]")).click();
    driver.findElement(By.xpath("//img[contains(@src,'https://res.cloudinary.com/futurewise/image/upload/v1730960221/myplanner/Vector55.svg')]")).click();
    driver.findElement(By.xpath("//img[contains(@src,'https://res.cloudinary.com/futurewise/image/upload/v1730960221/myplanner/Vector55.svg')]")).click();
    driver.findElement(By.xpath("//div[@id='dropZone5']/div/div/div/div[6]")).click();
    driver.findElement(By.xpath("//img[contains(@src,'https://res.cloudinary.com/futurewise/image/upload/v1730960221/myplanner/Vector55.svg')]")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-70']/span/mat-panel-title/p")).click();
    driver.findElement(By.id("mat-select-value-21")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-78']/span/mat-panel-title")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-79']/span/mat-panel-title")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-79']/span/mat-panel-title")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-80']/span/mat-panel-title/p")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-80']/span/mat-panel-title/p")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-81']/span/mat-panel-title")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-81']/span/mat-panel-title")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-82']/span/mat-panel-title")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-82']/span/mat-panel-title")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div")).click();
    driver.findElement(By.xpath("//img[contains(@src,'https://res.cloudinary.com/futurewise/image/upload/v1730960221/myplanner/Vector55.svg')]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div/div/div/div/div[3]/div[2]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-filter-multi/div[2]/div/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.xpath("//img[@alt='download icon']")).click();
    driver.findElement(By.xpath("//div[@id='mat-menu-panel-11']/div/button")).click();
    driver.findElement(By.xpath("//img[@alt='download icon']")).click();
    driver.findElement(By.xpath("//div[@id='mat-menu-panel-11']/div/button[2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Jinita Sonesh Dedhia'])[18]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Jinita Sonesh Dedhia'])[18]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Jinita Sonesh Dedhia'])[20]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Jinita Sonesh Dedhia'])[20]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Jinita Sonesh Dedhia'])[20]/following::*[name()='svg'][1]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Jinita Sonesh Dedhia'])[20]/following::*[name()='svg'][1]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Jinita Sonesh Dedhia'])[20]/following::*[name()='svg'][1]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-selection-multi/div/div/div[4]/div[2]/div[2]/button/span")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-0']/app-filter-and-add-client/div/div[3]/div[2]/button/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5189']/label/span")).click();
    driver.findElement(By.xpath("//button[@type='undefined']")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-0']/app-filter-and-add-client/div/div/div[2]/img")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-selection-multi/div/div/div[4]/div[2]/div[2]/button/span")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-1']/app-filter-and-add-client/div/div[3]/div[2]/button")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5212']/label/span")).click();
    driver.findElement(By.xpath("//table[@id='table-low']/tbody/tr[13]/td")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5217']/label/span")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-1']/app-filter-and-add-client/div/div[5]/div[2]/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-selection-multi/div/div/div[4]/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-selection-multi/div[2]/div/button[2]/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div[2]/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-selection-multi/div/div/div[4]/div[2]/button")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-4']/app-filter-and-add-client/div/div/div[2]/img")).click();
    driver.findElement(By.id("mat-input-77")).click();
    driver.findElement(By.id("mat-input-77")).clear();
    driver.findElement(By.id("mat-input-77")).sendKeys("nikhil");
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-selection-multi/div/div/div[4]/div[2]/button")).click();
    driver.findElement(By.id("mat-input-79")).click();
    driver.findElement(By.id("mat-input-79")).clear();
    driver.findElement(By.id("mat-input-79")).sendKeys("nikhil");
    driver.findElement(By.xpath("//mat-option[@id='mat-option-57']/span")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-5']/app-filter-and-add-client/div/div[5]/div[2]/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.id("mat-input-77")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-selection-multi/div/div/div[4]/div[2]/button")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-6']/app-filter-and-add-client/div/div[5]/div[2]/app-progress-button/div/button/span")).click();
    driver.findElement(By.id("mat-error-3")).click();
    try {
      assertEquals(driver.findElement(By.id("mat-error-3")).getText(), "This field is required.");
    } catch (Error e) {
      verificationErrors.append(e.toString());
    }
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-6']/app-filter-and-add-client/div/div/div[2]/img")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-selection-multi/div/div/div[4]/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-client-selection-multi/div[2]/div/button[2]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5751']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='-'])[44]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5751']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='-'])[44]/following::*[name()='svg'][1]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='-'])[44]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5751']/label/span")).click();
    driver.findElement(By.cssSelector("svg.mat-paginator-icon > path")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5936']/label/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5708']/label/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5708']/label/span")).click();
    driver.findElement(By.id("mat-input-81")).click();
    driver.findElement(By.id("mat-input-81")).clear();
    driver.findElement(By.id("mat-input-81")).sendKeys("sonesh");
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/table/tbody/tr[3]/td[7]/div/div/img")).click();
    driver.findElement(By.xpath("//mat-select[@id='mat-select-20']/div/div[2]")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-62']/span")).click();
    driver.findElement(By.id("mat-input-82")).click();
    driver.findElement(By.id("mat-input-82")).clear();
    driver.findElement(By.id("mat-input-82")).sendKeys("500");
    driver.findElement(By.id("mat-input-82")).sendKeys(Keys.ENTER);
    driver.findElement(By.xpath("//img[@alt='green tick icon']")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/table/tbody/tr[2]/td[7]/div/div/img")).click();
    driver.findElement(By.xpath("//img[@alt='green tick icon']")).click();
    driver.findElement(By.id("mat-input-83")).click();
    driver.findElement(By.id("mat-input-83")).clear();
    driver.findElement(By.id("mat-input-83")).sendKeys("");
    driver.findElement(By.xpath("//img[@alt='green tick icon']")).click();
    driver.findElement(By.id("mat-input-83")).click();
    driver.findElement(By.id("mat-input-83")).clear();
    driver.findElement(By.id("mat-input-83")).sendKeys("220");
    driver.findElement(By.xpath("//img[@alt='green tick icon']")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5708']/label/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5708']/label/span")).click();
    driver.findElement(By.id("mat-input-81")).click();
    driver.findElement(By.id("mat-input-81")).clear();
    driver.findElement(By.id("mat-input-81")).sendKeys("");
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6051']/label/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6051']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='-'])[44]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6051']/label/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6051']/label/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div[2]/div[2]/button")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div")).click();
    driver.findElement(By.xpath("//div[4]/div")).click();
    driver.findElement(By.xpath("//img[@alt='download icon']")).click();
    driver.findElement(By.xpath("//div[@id='mat-menu-panel-14']/div/button")).click();
    driver.findElement(By.xpath("//img[@alt='download icon']")).click();
    driver.findElement(By.xpath("//div[@id='mat-menu-panel-14']/div/button[2]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div/div/button/span")).click();
    driver.findElement(By.id("mat-input-77")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div[2]/div[2]/button")).click();
    driver.findElement(By.id("mat-select-value-27")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-73']/span")).click();
    driver.findElement(By.id("mat-input-82")).click();
    driver.findElement(By.id("mat-input-82")).clear();
    driver.findElement(By.id("mat-input-82")).sendKeys("10");
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-6']/app-amount-edit-and-error-popup/div[2]/div[2]/div[2]/div/button")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5331']/label/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div[2]/div[2]/button")).click();
    driver.findElement(By.id("mat-select-value-31")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-80']/span")).click();
    driver.findElement(By.id("mat-input-88")).click();
    driver.findElement(By.id("mat-input-88")).clear();
    driver.findElement(By.id("mat-input-88")).sendKeys("560");
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-8']/app-amount-edit-and-error-popup/div[2]/div[2]/div[2]/div/button")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5331']/label/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div/div[3]/div[2]/div[2]/button")).click();
    driver.findElement(By.id("mat-select-value-33")).click();
    driver.findElement(By.id("mat-input-89")).click();
    driver.findElement(By.id("mat-input-89")).clear();
    driver.findElement(By.id("mat-input-89")).sendKeys("500");
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-9']/app-amount-edit-and-error-popup/div[2]/div[2]/div[2]/div/button")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-amount-multi/div[2]/div/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.id("mat-input-95")).click();
    driver.findElement(By.id("mat-input-95")).click();
    driver.findElement(By.xpath("//img[@alt='download icon']")).click();
    driver.findElement(By.xpath("//div[@id='mat-menu-panel-15']/div/button")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-detail-multi/div/div[3]/div[2]/a")).click();
    driver.findElement(By.xpath("//div[@id='mat-menu-panel-15']/div/button[2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='-'])[10]/following::*[name()='svg'][1]")).click();
    driver.findElement(By.cssSelector("path")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-detail-multi/div/table/tbody/tr[7]/td[8]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-detail-multi/div/table/tbody/tr[8]/td[8]/div/img")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-12']/app-transaction-detail-edit-popup/div[2]/div/p")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-12']/app-transaction-detail-edit-popup/div/div[2]/img")).click();
    driver.findElement(By.id("mat-input-95")).click();
    driver.findElement(By.id("mat-input-95")).clear();
    driver.findElement(By.id("mat-input-95")).sendKeys("sonesh navinchandra dedhia");
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-detail-multi/div/table/tbody/tr[7]/td[8]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-detail-multi/div/table/tbody/tr[7]/td[8]/div/img")).click();
    driver.findElement(By.id("mat-select-value-45")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-100']/span")).click();
    driver.findElement(By.id("mat-select-value-47")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-97']/span")).click();
    driver.findElement(By.xpath("//div[@id='mat-select-value-49']/span/span")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-108']/span")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-13']/app-transaction-detail-edit-popup/div[2]/div[2]/div[2]/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.id("mat-input-95")).click();
    driver.findElement(By.id("mat-input-95")).clear();
    driver.findElement(By.id("mat-input-95")).sendKeys("");
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='-'])[30]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Axis Bank Ltd'])[1]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-transaction-detail-multi/div[2]/div/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='E103308'])[19]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='EUIN'])[1]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("//img[@alt='download icon']")).click();
    driver.findElement(By.xpath("//div[@id='mat-menu-panel-20']/div/button")).click();
    driver.findElement(By.xpath("//img[@alt='download icon']")).click();
    driver.findElement(By.id("mat-input-100")).click();
    driver.findElement(By.id("mat-input-100")).clear();
    driver.findElement(By.id("mat-input-100")).sendKeys("mandira");
    driver.findElement(By.xpath("//img[@alt='pencil icon']")).click();
    driver.findElement(By.id("mat-select-value-63")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-128']/span")).click();
    driver.findElement(By.id("mat-select-value-63")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-128']/span")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-16']/app-advisor-detail-edit-popup/div[2]/div[2]/div[2]/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.id("mat-input-100")).click();
    driver.findElement(By.id("mat-input-100")).click();
    driver.findElement(By.id("mat-input-100")).clear();
    driver.findElement(By.id("mat-input-100")).sendKeys("mitali");
    driver.findElement(By.xpath("//img[@alt='pencil icon']")).click();
    driver.findElement(By.id("mat-select-value-65")).click();
    driver.findElement(By.xpath("//mat-option[@id='mat-option-134']/span")).click();
    driver.findElement(By.xpath("//mat-dialog-container[@id='mat-dialog-17']/app-advisor-detail-edit-popup/div[2]/div[2]/div[2]/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.id("mat-input-100")).click();
    driver.findElement(By.id("mat-input-100")).clear();
    driver.findElement(By.id("mat-input-100")).sendKeys("");
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-advisor-detail-multi/div/div/div[2]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-advisor-detail-multi/div/div[3]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-advisor-detail-multi/div[2]/div/button[2]")).click();
    driver.findElement(By.xpath("//img[@alt='download icon']")).click();
    driver.findElement(By.xpath("//div[@id='mat-menu-panel-17']/div/button")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-review-multi/div/div/div[2]")).click();
    driver.findElement(By.xpath("//img[@alt='close icon']")).click();
    driver.findElement(By.xpath("//img[contains(@src,'https://res.cloudinary.com/futurewise/image/upload/v1669965314/myplanner/images/svg/crossbtn.svg')]")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-review-multi/div/div")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div/div[2]/app-review-multi/div[2]/div/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div/button")).click();
    driver.findElement(By.id("mat-input-90")).click();
    driver.findElement(By.id("mat-input-90")).clear();
    driver.findElement(By.id("mat-input-90")).sendKeys("P_3");
    driver.findElement(By.xpath("//mat-sidenav-content[@id='left']/div[2]/app-transactions/div[2]/div/app-mutual-fund-view/div[2]/div/app-crm-transaction/div/div[2]/div/table/tbody/tr/td[2]/div")).click();
    driver.findElement(By.xpath("//table[@id='table-low']/tbody/tr/td[2]")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("Aamod Rajan Panshikar");
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5759']/label/span")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("");
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("Bivob");
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5822']/label/span")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("");
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("Chaitya Dipesh Shah");
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-5885']/label/span")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("");
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Initiation Pending'])[21]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("Satish Singh");
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6008']/label/span")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("");
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Initiation Pending'])[21]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("//table[@id='table-low']/tbody/tr[3]/td[2]")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("Siddhant Chandrakant Jadhav");
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6098']/label/span")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("");
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Initiation Pending'])[21]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("Supriya Vinai Tiwari");
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6248']/label/span")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.id("mat-input-91")).clear();
    driver.findElement(By.id("mat-input-91")).sendKeys("");
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Initiation Pending'])[21]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Initiation Pending'])[21]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div[2]/div[2]/div[4]/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.id("mat-select-value-1807")).click();
    driver.findElement(By.xpath("//div[4]/div")).click();
    driver.findElement(By.id("mat-input-94")).click();
    driver.findElement(By.id("mat-input-94")).clear();
    driver.findElement(By.id("mat-input-94")).sendKeys("Testing(ignore email)");
    driver.findElement(By.xpath("//mat-radio-button[@id='mat-radio-287']/label")).click();
    driver.findElement(By.xpath("//mat-radio-button[@id='mat-radio-286']/label")).click();
    driver.findElement(By.xpath("//mat-radio-button[@id='mat-radio-293']/label/span[2]/p")).click();
    driver.findElement(By.xpath("//mat-radio-button[@id='mat-radio-292']/label/span[2]/p")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div[2]/div[2]/app-progress-button/div/button/span/span")).click();
    driver.findElement(By.xpath("//div[@id='iin-ucc-creation']/div[2]/div/button")).click();
    driver.findElement(By.xpath("//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div[2]/div[2]/div[3]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='search'])[3]/following::div[27]")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-38']/span/div")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6655']/label/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6656']/label/span")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6657']/label")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6658']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.xpath("//mat-tab-body[@id='mat-tab-content-0-0']/div/div/div[2]/div[2]/div[3]")).click();
    driver.findElement(By.xpath("//mat-expansion-panel-header[@id='mat-expansion-panel-header-40']/span/div")).click();
    driver.findElement(By.xpath("//mat-checkbox[@id='mat-checkbox-6720']/label/span")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='CLEAR ALL FILTERS'])[1]/following::button[1]")).click();
    driver.findElement(By.id("mat-input-91")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Initiation Pending'])[18]/following::*[name()='svg'][2]")).click();
    driver.findElement(By.xpath("(.//*[normalize-space(text()) and normalize-space(.)='Initiation Pending'])[20]/following::*[name()='svg'][2]")).click();
  }

  @AfterClass(alwaysRun = true)
  public void tearDown() throws Exception {
//    driver.quit();
    String verificationErrorString = verificationErrors.toString();
    if (!"".equals(verificationErrorString)) {
      fail(verificationErrorString);
    }
  }

  private boolean isElementPresent(By by) {
    try {
      driver.findElement(by);
      return true;
    } catch (NoSuchElementException e) {
      return false;
    }
  }

  private boolean isAlertPresent() {
    try {
      driver.switchTo().alert();
      return true;
    } catch (NoAlertPresentException e) {
      return false;
    }
  }

  private String closeAlertAndGetItsText() {
    try {
      Alert alert = driver.switchTo().alert();
      String alertText = alert.getText();
      if (acceptNextAlert) {
        alert.accept();
      } else {
        alert.dismiss();
      }
      return alertText;
    } finally {
      acceptNextAlert = true;
    }
  }
}
